- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    cloud: ospcloud
    name: "{{ item.instance_name }}"
    image: "{{ item.image }}"
    meta: "{{ item.meta }}"
    flavor: m2.small
    security_groups: "{{ item.security_group_name }}"
    key_name: ansible_ssh
    nics: net-name=int_network
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
      cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  loop: "{{instance_info}}"
  register: instanceip

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: "yes"
    server: "{{ item.instance_name }}"
    network: ext_network
    wait: "true"
    timeout: "180"
  loop: "{{instance_info}}"
  register: instancefloatingip

- name: start stopped
  os_server_actions:
    action: start
    auth:
    server:  "{{ item.instance_name }}"
    timeout: "200"
  loop: "{{instance_info}}"

- name: Show "{{ item.floating_ip }}" public IP
  debug: 
    var: item.floating_ip.floating_ip_address
  with_items: "{{ instancefloatingip.results }}"


- name: Wait for "{{ item.floating_ip }}" to be available
  wait_for:
    host: "{{ item.floating_ip.floating_ip_address }}"
    port: 22
    timeout: 600
  loop: "{{ instancefloatingip.results }}"